const iconSkills = [
    { title: 'HTML', logo: '/images/svgs/html.svg' },
    { title: 'CSS', logo: '/images/svgs/css.svg' },
    { title: 'JavaScript', logo: '/images/svgs/javascript.svg' },
    { title: 'GitHub', logo: '/images/svgs/github.svg' },
    { title: 'SQL', logo: '/images/svgs/sql.svg' },
    { title: 'Java', logo: '/images/svgs/java.svg' },
    { title: 'Python', logo: '/images/svgs/python.svg' },
    { title: 'React', logo: '/images/svgs/reactjs.svg' },
    { title: 'Angular', logo: '/images/svgs/angular.svg' },
    { title: 'Node.js', logo: '/images/svgs/nodejs.svg' },
    { title: 'Express.js', logo: '/images/svgs/expressjs.svg' },
    { title: 'Django', logo: '/images/svgs/django.svg' },
    { title: 'C#', logo: '/images/svgs/csharp.svg' },
    { title: '.NET', logo: '/images/svgs/dotnet.svg' },
    { title: 'Bootstrap', logo: '/images/svgs/bootstrap.svg' },
    { title: 'Sass', logo: '/images/svgs/sass.svg' },
    { title: 'MongoDB', logo: '/images/svgs/mongodb.svg' },
    { title: 'Firebase', logo: '/images/svgs/firebase.svg' },
    { title: 'Docker', logo: '/images/svgs/docker.svg' },
    { title: 'Kubernetes', logo: '/images/svgs/kubernetes.svg' },
    { title: 'TensorFlow', logo: '/images/svgs/tensorflow.svg' },
    { title: 'PyTorch', logo: '/images/svgs/pytorch.svg' },
    { title: 'Unity', logo: '/images/svgs/unity.svg' },
    { title: 'Swift', logo: '/images/svgs/swift.svg' },
    { title: 'Kotlin', logo: '/images/svgs/kotlin.svg' },
    { title: 'Flutter', logo: '/images/svgs/flutter.svg' },
    { title: 'TypeScript', logo: '/images/svgs/typescript.svg' },
    { title: 'Backbone.js', logo: '/images/svgs/backbonejs.svg' },
    { title: 'Ember.js', logo: '/images/svgs/emberjs.svg' },
    { title: 'Meteor.js', logo: '/images/svgs/meteorjs.svg' },
    { title: 'Next.js', logo: '/images/svgs/nextjs.svg' },
    { title: 'Nuxt.js', logo: '/images/svgs/nuxtjs.svg' },
    { title: 'Redux', logo: '/images/svgs/redux.svg' },
    { title: 'Spring Boot', logo: '/images/svgs/springboot.svg' },
    { title: 'Flask', logo: '/images/svgs/flask.svg' },
    { title: 'Laravel', logo: '/images/svgs/laravel.svg' },
    { title: 'Ruby', logo: '/images/svgs/ruby.svg' },
    { title: 'PHP', logo: '/images/svgs/php.svg' },
    { title: 'Go', logo: '/images/svgs/go.svg' },
    { title: 'Rust', logo: '/images/svgs/rust.svg' },
    { title: 'Vue.js', logo: '/images/svgs/vuejs.svg' },
    { title: 'jQuery', logo: '/images/svgs/jquery.svg' },
    { title: 'Postgre SQL', logo: '/images/svgs/postgressql.svg' },
    { title: 'Azure SQL Database', logo: '/images/svgs/azure_sql_database.svg' },
    { title: 'MySQL', logo: '/images/svgs/mysql.svg' },
    { title: 'SQLite', logo: '/images/svgs/sqllite.svg' },
    { title: 'Redis', logo: '/images/svgs/redis.svg' },
    { title: 'GraphQL', logo: '/images/svgs/graphql.svg' },
    { title: 'Fast API', logo: '/images/svgs/fastapi.svg' },
    { title: 'AWS', logo: '/images/svgs/aws.svg' },
    { title: 'Azure', logo: '/images/svgs/azure.svg' },
    { title: 'Google Cloud', logo: '/images/svgs/google_cloud.svg' },
    { title: 'Heroku', logo: '/images/svgs/heroku.svg' },
    { title: 'Netlify', logo: '/images/svgs/netlify.svg' },
    { title: 'Digital Ocean', logo: '/images/svgs/digital_ocean.svg' },
    { title: 'Jenkins', logo: '/images/svgs/jenkins.svg' },
    { title: 'CircleCI', logo: '/images/svgs/circlecl.svg' },
    { title: 'Travis CI', logo: '/images/svgs/traviscl.svg' },
    { title: 'GitLab CI/CD', logo: '/images/svgs/gitlab.svg' },
    { title: 'Jira', logo: '/images/svgs/jira.svg' },
    { title: 'Confluence', logo: '/images/svgs/confluence.svg' },
    { title: 'Trello', logo: '/images/svgs/trello.svg' },
    { title: 'Slack', logo: '/images/svgs/slack.svg' },
    { title: 'Sanity', logo: '/images/svgs/sanity.svg' },
    { title: 'VS Code', logo: '/images/svgs/vscode.svg' },
    { title: 'Atom', logo: '/images/svgs/atom.svg' },
    { title: 'Eclipse', logo: '/images/svgs/eclipse.svg' },
    { title: 'IntelliJ IDEA', logo: '/images/svgs/intellijidea.svg' },
    { title: 'Android', logo: '/images/svgs/android.svg' },
    { title: 'Xcode', logo: '/images/svgs/xcode.svg' },
    { title: 'Android Studio', logo: '/images/svgs/android_studio.svg' },
    { title: 'Visual Studio', logo: '/images/svgs/vsstudio.svg' },
    { title: 'Postman', logo: '/images/svgs/postmen.svg' },
    { title: 'Open Api', logo: '/images/svgs/openapi.svg' },
    { title: 'Insomnia', logo: '/images/svgs/insomnia.svg' },
    { title: 'Swagger', logo: '/images/svgs/swagger.svg' },
    { title: 'Grafana', logo: '/images/svgs/grafana.svg' },
    { title: 'Prometheus', logo: '/images/svgs/prometheus.svg' },
    { title: 'Sketch', logo: '/images/svgs/Sketch.svg' },
    { title: 'Socket.io', logo: '/images/svgs/socketio.svg' },
    { title: 'Solidity', logo: '/images/svgs/solidity.svg' },
    { title: 'Yarn', logo: '/images/svgs/yarn.svg' },
    { title: 'Wordpress', logo: '/images/svgs/wordpress.svg' },
    { title: 'Vite', logo: '/images/svgs/vite.svg' },
    { title: 'Xamreen', logo: '/images/svgs/xamreen.svg' },
    { title: 'Web Assembly', logo: '/images/svgs/webassembly.svg' },
    { title: 'Vite.js', logo: '/images/svgs/vitejs.svg' },
    { title: 'Vercel', logo: '/images/svgs/vercel.svg' },
    { title: 'Unreal Engine', logo: '/images/svgs/unreal_engine.svg' },
    { title: 'Three.js', logo: '/images/svgs/threejs.svg' },
    { title: 'TailWindCss', logo: '/images/svgs/tailwindcss.svg' },
    { title: 'SSH', logo: '/images/svgs/ssh.svg' },
    { title: 'Scala', logo: '/images/svgs/scala.svg' },
    { title: 'Realm', logo: '/images/svgs/realm.svg' },
    { title: 'React Bootstrap', logo: '/images/svgs/react_bootstrap.svg' },
    { title: 'R', logo: '/images/svgs/r.svg' },
    { title: 'Pyscript', logo: '/images/svgs/pyscript.svg' },
    { title: 'Pycharm', logo: '/images/svgs/pycharm.svg' },
    { title: 'Powershell', logo: '/images/svgs/powershell.svg' },
    { title: 'PostCss', logo: '/images/svgs/postcss.svg' },
    { title: 'Perl', logo: '/images/svgs/perl.svg' },
    { title: 'oracle', logo: '/images/svgs/oracle.svg' },
    { title: 'Objective C', logo: '/images/svgs/objective_c.svg' },
    { title: 'NPM', logo: '/images/svgs/npm.svg' },
    { title: 'Nginx', logo: '/images/svgs/nginx.svg' },
    { title: 'Nestjs', logo: '/images/svgs/nestjs.svg' },
    { title: 'ML', logo: '/images/svgs/ml.svg' },
    { title: 'MaterialUi', logo: '/images/svgs/materialui.svg' },
    { title: 'Lua', logo: '/images/svgs/lua.svg' },
    { title: 'Kaggle', logo: '/images/svgs/kaggle.svg' },
    { title: 'Jupyter', logo: '/images/svgs/jupiter.svg' },
    { title: 'Julia', logo: '/images/svgs/julia.svg' },
    { title: 'Json', logo: '/images/svgs/json.svg' },
    { title: 'Ionos', logo: '/images/svgs/ionos.svg' },
    { title: 'Ionic', logo: '/images/svgs/ionic.svg' },
    { title: 'Haskell', logo: '/images/svgs/haskell.svg' },
    { title: 'Groovy', logo: '/images/svgs/groovy.svg' },
    { title: 'Gradle', logo: '/images/svgs/gradle.svg' },
    { title: 'Google', logo: '/images/svgs/google.svg' },
    { title: 'Git', logo: '/images/svgs/git.svg' },
    { title: 'Ghost', logo: '/images/svgs/ghost.svg' },
    { title: 'Gcc', logo: '/images/svgs/gcc.svg' },
    { title: 'F#', logo: '/images/svgs/fsharp.svg' },
    { title: 'Figma', logo: '/images/svgs/figma.svg' },
    { title: 'Fastify', logo: '/images/svgs/fastify.svg' },
    { title: 'Electron.Js', logo: '/images/svgs/electronjs.svg' },
    { title: 'Data Grip', logo: '/images/svgs/datagrip.svg' },
    { title: 'Fortran', logo: '/images/svgs/fortran.svg' },
    { title: 'Data Science', logo: '/images/svgs/data_science.svg' },
    { title: 'Dart', logo: '/images/svgs/dart.svg' },
    { title: 'C++', logo: '/images/svgs/cpp.svg' },
    { title: 'Core.js', logo: '/images/svgs/corejs.svg' },
    { title: 'Coffee Script', logo: '/images/svgs/coffeescript.svg' },
    { title: 'Cloudflare', logo: '/images/svgs/cloudflare.svg' },
    { title: 'Closure Script', logo: '/images/svgs/closurescript.svg' },
    { title: 'C', logo: '/images/svgs/c.svg' },
    { title: 'Bulma', logo: '/images/svgs/bulma.svg' },
    { title: 'Blender', logo: '/images/svgs/blender.svg' },
    { title: 'Bit Bucket', logo: '/images/svgs/bitbucket.svg' },
    { title: 'Assembly', logo: '/images/svgs/assembly.svg' },
    { title: 'Apple', logo: '/images/svgs/apple.svg' },
    { title: 'After Effect', logo: '/images/svgs/after_effect.svg' },
    { title: 'Adobe Photoshop', logo: '/images/svgs/adobe_photoshop.svg' },
    { title: 'Adobe Xd', logo: '/images/svgs/adobexd.svg' },
]